name: push_to_prod
on: 
  workflow_dispatch:

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
    - name: Check out master repo
      uses: actions/checkout@v2.3.4
      with:
        path: master
        persist-credentials: false

    - name: Login to DockerHub
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Publish Addon Image
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target master/AlphaESS_Monitor_Hass
